### ISSUE TITLE
Make AndroidPlayInstallReferrer.installReferrer not nullable

### ISSUE THREAD

**Issue by lschmierer** [lschmierer/android_play_install_referrer#12]
`AndroidPlayInstallReferrer.installReferrer` should either return `Future<ReferrerDetails>` (instead of `Future<ReferrerDetails?>`) on success or throw an error (iOS, missing Google Services, native errors).

The plugin should never return null.

**Comment by srcnysf** [comment]
Agree on that

**Comment by lschmierer** [comment]
Fixed with 0.2.0 release
