### ISSUE TITLE
The package name should be passed in as a String to to the plugin to work

### ISSUE THREAD

**Issue by Asim-2000** [lschmierer/android_play_install_referrer#15]
The plugin will only work for you until and unless we change the package name for the caller. Hence, we need to accept it as an argument for the package. and based on the input, we need to give the response.

Following are the details mentioned in the Play Install Referrer API.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/46053827/129174960-f7134f4c-545a-4ea7-8ab2-dd70765d1752.png">

And this is the implementation of the Channel:
```dart
class AndroidPlayInstallReferrer {
  static const MethodChannel _channel =
      const MethodChannel('de.lschmierer.android_play_install_referrer');
```
It should be something like this

```dart
class AndroidPlayInstallReferrer {
  static const MethodChannel _channel =
      const MethodChannel(`$package_name`);
```

**Comment by lschmierer** [comment]
I do not see how the name of the Flutter `MethodChannel` is related to the Install Referrer API.
The `MethodChannel` is only used for communication between the Flutter app and the native plugin.

https://github.com/lschmierer/android_play_install_referrer/blob/master/android/src/main/kotlin/de/lschmierer/android_play_install_referrer/AndroidPlayInstallReferrerPlugin.kt

The channel name itself is arbitrary. It just has to be the same on the Dart side (your cited code) and the Android side (the link above).


Further, your screenshot shows the documentation of the Play Installer AIDL interface (https://developer.android.com/google/play/installreferrer/igetinstallreferrerservice) which is not used in this plugin.
Instead we use the Play Installer Java/Kotlin library (https://developer.android.com/google/play/installreferrer/library) which makes it easier to work with from Java/Kotlin.
Especially, it does not require us to pass `package_name`.
