### ISSUE TITLE
How to build referrer url 

### ISSUE THREAD

**Issue by Microinstance** [lschmierer/android_play_install_referrer#2]
Hi, I have used this plugin in my current Project. But every time it is showing organic. Please guide me how to create referrer url which can track properly. 

Thanks

**Comment by lschmierer** [comment]
This library passes the value of the `referrer` parameter of the Play Store URI.

For example for `https://play.google.com/store/apps/details?id=life.snuzzle.snuzzle3&referrer=xyz`, `xyz` would be passed as referrer.

I am using it for example in https://snuzzle.life/p/U43j8I3vvyYNDUo39PtD#kZl65XOuWt32eS0D9vKXTWD11e55sy5xXLfzmC/j0MQ= to open the correct puzzle on first launch after install.

https://snuzzle.life/p/U43j8I3vvyYNDUo39PtD#kZl65XOuWt32eS0D9vKXTWD11e55sy5xXLfzmC/j0MQ=
redirects to https://play.google.com/store/apps/details?id=life.snuzzle.snuzzle3&referrer=https%3A%2F%2Fsnuzzle.life%2Fp%2FU43j8I3vvyYNDUo39PtD%23kZl65XOuWt32eS0D9vKXTWD11e55sy5xXLfzmC%2Fj0MQ%3D encoding the original URL as referrer.

The app knows how to handle the original URI.

Please note that this only works on Android and ONLY if the app is installed from the Play Store. I was not able to figure out any way to test this behaviour besides publishing it in the Store. You can probably use Alpha or Beta testing  though.
