### ISSUE TITLE
PlatformException(PERMISSION_ERROR, App is not allowed to bind to the Service., null, null)

### ISSUE THREAD

**Issue by wl1395182472** [lschmierer/android_play_install_referrer#22]
PlatformException(PERMISSION_ERROR, App is not allowed to bind to the Service., null, null)
![image](https://user-images.githubusercontent.com/55087590/171579329-939e850e-9117-4049-8236-3f9c98aa1f6d.png)
![image](https://user-images.githubusercontent.com/55087590/171579405-5a6f072e-f721-427c-a3b5-66374e7b2428.png)
![image](https://user-images.githubusercontent.com/55087590/171579522-6dfcce4d-b2f8-4b1e-8aa7-db4fa6e06f82.png)
flutter doctor is normal

**Comment by lschmierer** [comment]
Hi, on what device are you getting this error?

Does this also happen in the example app?

**Comment by wl1395182472** [comment]
> Hi, on what device are you getting this error?
> 
> Does this also happen in the example app?

it happens at android,i have not tried the example app

**Comment by lschmierer** [comment]
This sounds like an issue on the device itself (which manufacturer? are Play services available?).

You can e.g. check if this app on the Play Store works with your device https://play.google.com/store/apps/details?id=com.normsdev.install.referrer&hl=de&gl=US

**Comment by wl1395182472** [comment]
> This sounds like an issue on the device itself (which manufacturer? are Play services available?).
> 
> You can e.g. check if this app on the Play Store works with your device https://play.google.com/store/apps/details?id=com.normsdev.install.referrer&hl=de&gl=US

thank you ,it works

**Comment by lschmierer** [comment]
This indicates, that this is in fact an issue with this library.

Unfortunately, currently I have no idea what should have gone wrong 🤔

**Comment by wl1395182472** [comment]
it is my fault.it is about android permission.
![image](https://user-images.githubusercontent.com/55087590/172107858-d728f343-d0a7-4d48-9203-0e4581a5fcdf.png)

**Comment by wl1395182472** [comment]
> it is my fault.it is about android permission. ![image](https://user-images.githubusercontent.com/55087590/172107858-d728f343-d0a7-4d48-9203-0e4581a5fcdf.png)

com.google.android.c2dm.permission.RECEIVE
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE

**Comment by lschmierer** [comment]
@wl1395182472 may I ask, why have your removed those permissions in the first place?

I am gonna close this issue as it seems to be resolved
