### ISSUE TITLE
Update to a newer version of kotlin

### ISSUE THREAD

**Issue by joshstorms** [lschmierer/android_play_install_referrer#27]
When attempting to use v0.2.1 with the most recent version of Flutter (v3.10.0), the following build error occurs:

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':android_play_install_referrer' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
```

Can you update the version of kotlin specified in `build.gradle`?

**Comment by lschmierer** [comment]
Can you submit a PR? I am very busy at the moment

**Comment by joshstorms** [comment]
> Can you submit a PR? I am very busy at the moment

Sure.  No problem.  It doesn't look like I currently have permission in the repo to create a branch.  Can you help with that?

**Comment by lschmierer** [comment]
The normal workflow on GitHub is for you to fork the repository and then to create a Pull Request from your repository to mine.
