### ISSUE TITLE
utm_sorce and utm_medium print "(not%20set)"

### ISSUE THREAD

**Issue by shinyo17** [lschmierer/android_play_install_referrer#9]
I post the app for open test app, i used the link "https://play.google.com/store/apps/details?id=com.developer.petnerdeveloper&referrer=xyz&utm_source=ravi&utm_medium=ravi"

but it didn't work. it just print (not%20set)
how can i get the "ravi"? I don't know why utm_source and utm_medium not print the "ravi".

**Comment by lschmierer** [comment]
I can not see the app using your link.

As I mentioned here https://github.com/lschmierer/android_play_install_referrer/issues/1#issuecomment-599038268, the referrer is not  set for Alpha and Beta distribution by the Play Store.

**Comment by yakshpanchal** [comment]
@bhargav6744  Have you found any solution?
